[Created] Kakao Login API Created
wecode-bootcamp-korea/27-2nd-Quest101-backend pull request #4
Opened 2021-12-16 06:55 UTC by haileyjpark

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 소셜 로그인구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 인가 데코레이터 구현
2. 프론트엔드에서 받아온 카카오 토큰으로 카카오에서 사용자 정보를 가져와서 새로운 토큰을 발급하는 소셜 로그인 프로세스 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- Third Party에서 사용자 정보를 받아오는 프로세스를 이해하게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2021-12-16 10:06 UTC, lordmyshepherd requested changes

2021-12-16 10:06 UTC, lordmyshepherd commented on users/views.py
> +class KakaoSignInView(View):
아래와 같이 Kakao API 관련된 로직은 class로 그룹핑할 수 있습니다.  

그렇게 되면 kakao API 관련된 로직은 하나의 class에서 관리하면 된다는 장점이 있고, 만약에 나중에 kakao api 호출부의 수정일 있을 경우 `KakaoLoginView`를 수정할 필요가 없이 `KakaoAPI` 클래스만 수정하면 됩니다. 

결국 Kakao API를 호출하는 위치에서는 Interface만 알고 사용하면 되고 내부적으로 어떻게 구현되었는지 알 필요가 없습니다.

```python
class KakaoAPI:
    def __init__(self, access_token):
        self.access_token = access_token
        self.user_url     = 'https://kapi.kakao.com/v2/user/me'
				self.map_url      = 

    def get_kakao_user(self):
        headers = {"Authorization": f"Bearer ${self.access_token}"}
        response = requests.get(self.user_url, headers=headers)
    
        if not response.status_code == 200:
	    return
        
        return response.json()

    def get_location():
        return   

class KakaoLoginView(View):
    def post(self, request):
        try:
            kakao_access_token = request.headers['Authorization']
            kakao_user = KakaoAPI(kakao_access_token)

```

2021-12-16 10:06 UTC, lordmyshepherd commented on users/views.py
> +            response      = requests.get(kakao_url, headers=kakao_headers, timeout = 5)
timeout 👍🏻

2021-12-16 10:06 UTC, lordmyshepherd commented on users/views.py
> +            )
get_or_create()에 `kakao_id`,  `name`,`email`, `profile_image` 모든 컬럼이 들어가게되면 발생할 수 있는 버그는 없는 건가요?

2021-12-16 10:06 UTC, lordmyshepherd commented on users/views.py
> +            response      = requests.get(kakao_url, headers=kakao_headers, timeout = 5)
보통 이렇게 third party 서버의 응답의 성공/실패 여부를 판단할때에는 status 코드로 비교해야 명확하고 디버깅하기 쉽습니다.

```
class KakaoLoginView(View):
    def post(self, request):
        try:
            kakao_access_token    = request.headers['Authorization']
            kakao_user_api_url    = '<https://kapi.kakao.com/v2/user/me>'
            headers     = {"Authorization": f"Bearer ${kakao_access_token}"}

            response = requests.get(kakao_user_api_url, headers=headers)

            if not response.status_code == 200:
		              return JsonResponse...

            ..

```

2021-12-16 14:19 UTC, haileyjpark commented on users/views.py
> +            response      = requests.get(kakao_url, headers=kakao_headers, timeout = 5)
수정했습니다 감사합니다!

2021-12-17 00:05 UTC, haileyjpark commented on users/views.py
> +            )
에러 예외처리를 말씀하시는 걸까요? 
이 부분 이해가 잘 안되어서 혹시 구두로 설명해주실 수 있나요?

2021-12-17 03:25 UTC, haileyjpark commented on users/views.py
> +            )
해당 부분 수정했습니다 감사합니다!

2021-12-17 03:25 UTC, haileyjpark commented on users/views.py
> +class KakaoSignInView(View):
수정했습니다 감사합니다!

2021-12-17 09:27 UTC, lordmyshepherd requested changes

2021-12-17 09:27 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({'message': 'INVALID KAKAO USER'}, status=400)
line 31, 32 코드도 line 19로 옮겨주세요! 왜 이 로직은 밖으로 나와 있는 건가요?

2021-12-17 10:43 UTC, haileyjpark commented on users/views.py
> +                return JsonResponse({'message': 'INVALID KAKAO USER'}, status=400)
수정했습니다 감사합니다!

2021-12-18 01:04 UTC, lordmyshepherd commented
LGTM 👍🏻

2021-12-18 01:04 UTC, merged