add:likeview
wecode-bootcamp-korea/27-2nd-Quest101-backend pull request #6
Opened 2021-12-20 14:32 UTC by whytili89

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 좋아요를 생성하고 삭제하는 기능구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.get_or_create메소드를 사용하여 로그인 한 유저가 좋아요를 누른 데이터가 있으면
 삭제하고 없으면 생성하도록 기능을 구현하였습니다.

2. 해당 강의에 좋아요 수를 볼 수 있습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
get_or_create 메소드에 대해 알게되었고 활용할 수 있게 되었습니다.
<br />

## :: 기타 질문 및 특이 사항

2021-12-21 07:58 UTC, lordmyshepherd requested changes

2021-12-21 07:58 UTC, lordmyshepherd commented on users/tests.py
> +#             kakao_id      = "01924234",
주석 지워주세요~

2021-12-21 07:58 UTC, lordmyshepherd commented on products/views.py
> +            like, is_like = Like.objects.get_or_create(course_id=course_id, user_id=request.user.id)
```suggestion
            like, created = Like.objects.get_or_create(course_id=course_id, user_id=request.user.id)
```

2021-12-21 07:58 UTC, lordmyshepherd commented on products/views.py
> +            if not is_like:
```suggestion
            if not created:
```

2021-12-21 07:58 UTC, lordmyshepherd commented on products/views.py
> +    def post(self,request,course_id):
course_id는 body로 받도록 수정 부탁드립니다!

2021-12-22 06:06 UTC, whytili89 commented on users/tests.py
> +#             kakao_id      = "01924234",
수정하였습니다.

2021-12-22 06:06 UTC, whytili89 commented on products/views.py
> +            like, is_like = Like.objects.get_or_create(course_id=course_id, user_id=request.user.id)
수정하였습니다

2021-12-22 06:06 UTC, whytili89 commented on products/views.py
> +    def post(self,request,course_id):
수정하였습니다.

2021-12-22 06:06 UTC, whytili89 commented on products/views.py
> +            if not is_like:
수정하였습니다.

2021-12-22 23:35 UTC, closed without merging